services:
  db:
    # image: tkenzo/migration_container:0.1.0
    image: public.ecr.aws/docker/library/mysql:9.6
    # image: mysql:9.2
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./sqlfiles:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mysql --user=$$MYSQL_USER --password=$$MYSQL_ROOT_PASSWORD --host=localhost --execute \"SHOW DATABASES;\" || exit 1"
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 20s

  # adminer:
  #   depends_on:
  #     db: 
  #       condition: service_healthy
  #   image: adminer
  #   ports:
  #     - 8080:8080
  #   healthcheck:
  #     test: ["CMD", "curl", "http://localhost:8080"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 20s

  api:
    depends_on:
      db: 
        condition: service_healthy
    build:
      context: .
      dockerfile: python.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: db
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl","http://localhost:8000/users"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  react: 
    build:
      context: .
      dockerfile: react.Dockerfile
    ports:
      - 3000:3000
    environment:
      - REACT_APP_SERVER_PORT=8000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      api: 
        condition: service_healthy
    command: sh -c "npm ci && npm start"
    healthcheck:
      test: ["CMD", "curl","http://localhost:3000/users"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s