services:
  db:
    # image: tkenzo/migration_container:0.1.0
    image: mysql:9.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./sqlfiles:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mysql --user=$$MYSQL_USER --password=$$MYSQL_ROOT_PASSWORD --host=localhost --execute \"SHOW DATABASES;\" || exit 1"
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 20s

  adminer:
    depends_on:
      db: 
        condition: service_healthy
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    depends_on:
      db: 
        condition: service_healthy
    build:
      context: .
      dockerfile: python.Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: db
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/users"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s